# Generated by Django 3.2.4 on 2024-03-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=32)),
                ('pro_description', models.TextField()),
                ('pro_image', models.TextField()),
                ('pro_code', models.CharField(max_length=32)),
                ('pro_range', models.CharField(max_length=32)),
                ('pro_features', models.TextField()),
                ('pro_price', models.IntegerField()),
                ('pro_price_plumber', models.IntegerField()),
                ('pro_price_prime', models.IntegerField()),
                ('pro_price_per_user', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
    ]
